# Generated by Django 4.2.24 on 2025-10-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'پیام دریافتی', 'verbose_name_plural': 'پیام\u200cهای تماس باما '},
        ),
    ]
