# Generated by Django 4.2.24 on 2025-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_ar',
            field=models.TextField(null=True, verbose_name='متن مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=models.TextField(null=True, verbose_name='متن مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_fa',
            field=models.TextField(null=True, verbose_name='متن مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان'),
        ),
    ]
